docs: Update config file instructions
btbristow/tutorials pull request #3
Opened 2024-12-16 16:37 UTC by telnetdoogie

Small update to the cert_config.json edit instructions

2024-12-16 16:43 UTC, telnetdoogie commented
Also added a small change to the scheduled task commands for the update script

2025-01-01 17:17 UTC, btbristow requested changes
@telnetdoogie How about:

> In a text editor, open `cert_config.json` and add your certificate's Common Name (CN) and file path, obtained from the Certbot directory:

It's ok not to call the file "newly created" since that's explained in the prior step. For saying the update script should have populated the CN names, I'm struggling with that phrasing. The user needs to add the path and CN manually based on what Certbot created, right?

2025-01-01 17:20 UTC, btbristow requested changes
@telnetdoogie How about:

cd /path/to/script # Change into the script directory which holds `cert_config.json`

2025-01-01 17:21 UTC, btbristow approved these changes

2025-01-01 20:07 UTC, btbristow approved these changes

2025-01-01 20:09 UTC, merged